import { brandName } from "@/config/config";
import QueryClientProvider from "@/context/react-query/QueryClientProvider";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: brandName,
  description: "Generated by create next app",
  metadataBase: new URL(process.env.VERCEL_URL || "http://localhost:3000"),
  keywords: ["Keyword 1", "Keyword 2"],
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="theme" lang="en">
      <body className={`${inter.className}  antialiased size-full`}>
        <QueryClientProvider>{children}</QueryClientProvider>
        <Toaster />
      </body>
    </html>
  );
}
